[environments]
  [environments.development]
    name = "sample-web-development"
    namespace = "development"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
  [environments.staging]
    name = "sample-web-staging"
    namespace = "staging"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
